# ASP.NET Core (.NET Framework) - Build & Deploy with Azure SQL

trigger:
- master  # Déclenche sur la branche master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscription: 'soniaconnection' # Connexion de service à Azure
  webAppName: 'soniaweb'               # Nom de la Web App
  sqlConnectionString: '$(SQL_CONNECTION_STRING)' # Injecté comme secret variable dans Azure DevOps

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: >
      /p:DeployOnBuild=true 
      /p:WebPublishMethod=Package 
      /p:PackageAsSingleFile=true 
      /p:SkipInvalidConfigurations=true 
      /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" 
      /p:DeployIisAppPath="Default Web Site"
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# Déployer sur Azure Web App avec AzureRmWebAppDeployment
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    WebAppName: '$(webAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
  displayName: 'Deploy to Azure Web App'


